name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pip and run quick checks
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          echo "Skipping heavy dependency install in CI; customize this step if you want full install"

      - name: Run backend tests (if present)
        working-directory: backend
        run: |
          if [ -d tests ] || ls *.py 1>/dev/null 2>&1; then
            pip install pytest || true
            pytest -q || true
          else
            echo "No tests found"
          fi

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        working-directory: backend
        run: |
          docker build -t pms-backend:latest .
